package main

import (
	"log/slog"
	"os"

	"github.com/tararahuuw/ragsytem/internal/config"
	"github.com/tararahuuw/ragsytem/internal/database"
	cacheinfra "github.com/tararahuuw/ragsytem/internal/infra/cache"
	minioinfra "github.com/tararahuuw/ragsytem/internal/infra/minio"
	sentryinfra "github.com/tararahuuw/ragsytem/internal/infra/sentry"
	"github.com/tararahuuw/ragsytem/internal/logger"
	"github.com/tararahuuw/ragsytem/internal/router"

	// docs is generated by swag; blank import registers the swagger spec.
	_ "github.com/tararahuuw/ragsytem/docs"
)

// @title           RAG System API
// @version         1.0
// @description     Backend API for the RAG System (NotebookLM-like document Q&A).
// @termsOfService  http://swagger.io/terms/
// @contact.name    RAG System Team
// @license.name    Proprietary
// @host            localhost:8080
// @BasePath        /api/v1
// @schemes         http https
//
// @securityDefinitions.apikey	BearerAuth
// @in							header
// @name						Authorization
// @description					Type "Bearer" followed by a space and the access token.
func main() {
	cfg := config.Load()
	logger.Init(cfg.AppEnv)

	// Start Sentry, then wrap the logger so every error log is also shipped there.
	// flush drains buffered events on exit; os.Exit skips defers, so fatal() below
	// flushes explicitly before exiting.
	flush := sentryinfra.Init(cfg)
	defer flush()
	if cfg.SentryDSN != "" {
		logger.EnableSentry(logger.ParseLevel(cfg.SentryLevel))
	}

	fatal := func(msg string, err error) {
		slog.Error(msg, "error", err)
		flush()
		os.Exit(1)
	}

	db, err := database.Connect(cfg)
	if err != nil {
		fatal("failed to connect to database", err)
	}
	if err := database.Migrate(db); err != nil {
		fatal("failed to run migrations", err)
	}

	store, err := minioinfra.New(cfg)
	if err != nil {
		fatal("failed to connect to object storage (minio)", err)
	}

	// Cache (Redis) is optional: a no-op when disabled, so this never fails.
	cacheClient := cacheinfra.New(cfg)
	defer cacheClient.Close()

	r := router.New(cfg, db, store, cacheClient)

	slog.Info("server starting",
		"app", cfg.AppName,
		"env", cfg.AppEnv,
		"addr", cfg.ServerAddr(),
		"swagger", "/swagger/index.html",
	)
	if err := r.Run(cfg.ServerAddr()); err != nil {
		fatal("server error", err)
	}
}
