package main

import (
	"log/slog"
	"os"

	"github.com/tararahuuw/ragsytem/internal/config"
	"github.com/tararahuuw/ragsytem/internal/database"
	minioinfra "github.com/tararahuuw/ragsytem/internal/infra/minio"
	"github.com/tararahuuw/ragsytem/internal/logger"
	"github.com/tararahuuw/ragsytem/internal/router"

	// docs is generated by swag; blank import registers the swagger spec.
	_ "github.com/tararahuuw/ragsytem/docs"
)

// @title           RAG System API
// @version         1.0
// @description     Backend API for the RAG System (NotebookLM-like document Q&A).
// @termsOfService  http://swagger.io/terms/
// @contact.name    RAG System Team
// @license.name    Proprietary
// @host            localhost:8080
// @BasePath        /api/v1
// @schemes         http https
//
// @securityDefinitions.apikey	BearerAuth
// @in							header
// @name						Authorization
// @description					Type "Bearer" followed by a space and the access token.
func main() {
	cfg := config.Load()
	logger.Init(cfg.AppEnv)

	db, err := database.Connect(cfg)
	if err != nil {
		slog.Error("failed to connect to database", "error", err)
		os.Exit(1)
	}
	if err := database.Migrate(db); err != nil {
		slog.Error("failed to run migrations", "error", err)
		os.Exit(1)
	}

	store, err := minioinfra.New(cfg)
	if err != nil {
		slog.Error("failed to connect to object storage (minio)", "error", err)
		os.Exit(1)
	}

	r := router.New(cfg, db, store)

	slog.Info("server starting",
		"app", cfg.AppName,
		"env", cfg.AppEnv,
		"addr", cfg.ServerAddr(),
		"swagger", "/swagger/index.html",
	)
	if err := r.Run(cfg.ServerAddr()); err != nil {
		slog.Error("server error", "error", err)
		os.Exit(1)
	}
}
