// Package auth holds the request/response DTOs for the auth module.
package auth

// RegisterRequest is the payload for POST /auth/register.
type RegisterRequest struct {
	Name             string `json:"name" binding:"required" example:"John Doe"`
	Email            string `json:"email" binding:"required,email" example:"john@example.com"`
	Password         string `json:"password" binding:"required,min=6" example:"secret123"`
	OrganizationCode string `json:"organization_code" binding:"required" example:"pln"`
}

// BulkRegisterItem is one entry in a bulk register request. Password is
// auto-generated by the server, so it is NOT part of the input.
type BulkRegisterItem struct {
	Name             string `json:"name" example:"John Doe"`
	Email            string `json:"email" example:"john@example.com"`
	OrganizationCode string `json:"organization_code" example:"pln"`
}

// BulkRegisterResultItem is the per-user outcome (partial-success model).
type BulkRegisterResultItem struct {
	Index        int    `json:"index"`
	Email        string `json:"email"`
	Status       string `json:"status" example:"created"` // created | failed
	ID           uint   `json:"id,omitempty"`
	TempPassword string `json:"temp_password,omitempty"` // shown once, only on success
	ErrorCode    string `json:"error_code,omitempty"`
	Error        string `json:"error,omitempty"`
}

// BulkRegisterResponse summarizes a bulk register run.
type BulkRegisterResponse struct {
	Total        int                      `json:"total"`
	SuccessCount int                      `json:"success_count"`
	FailedCount  int                      `json:"failed_count"`
	Results      []BulkRegisterResultItem `json:"results"`
}

// LoginRequest is the payload for POST /auth/login.
type LoginRequest struct {
	Email    string `json:"email" binding:"required,email" example:"john@example.com"`
	Password string `json:"password" binding:"required" example:"secret123"`
}

// RefreshRequest is the payload for POST /auth/refresh.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token" binding:"required"`
}

// ChangePasswordRequest is the payload for POST /auth/change-password.
type ChangePasswordRequest struct {
	OldPassword string `json:"old_password" binding:"required" example:"secret123"`
	NewPassword string `json:"new_password" binding:"required,min=6" example:"newSecret456"`
}

// ForgotPasswordRequest is the payload for POST /auth/forgot-password.
type ForgotPasswordRequest struct {
	Email string `json:"email" binding:"required,email" example:"john@example.com"`
}

// ResetPasswordRequest is the payload for POST /auth/reset-password.
type ResetPasswordRequest struct {
	Token       string `json:"token" binding:"required"`
	NewPassword string `json:"new_password" binding:"required,min=6" example:"newSecret456"`
}

// TokenResponse carries the issued JWT pair.
type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token,omitempty"`
	TokenType    string `json:"token_type" example:"Bearer"`
	ExpiresIn    int64  `json:"expires_in" example:"900"` // access token TTL in seconds
}
